apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-performance-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-performance-sc
