apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfsv3-mount-sc
provisioner: nfs.csi.ngxstorage.com
parameters:
  blocksize: "128k" # 4k, 8k, 16k, 32k, 64k, 128k, 256k, 512k, 1024k
  deduplication: "on" # "on", ""
  compression: "on" # "on", ""
volumeBindingMode: Immediate
reclaimPolicy: Delete
mountOptions:
  # Force NFSv3 for this class to test mount option propagation.
  - nfsvers=3 # nfsvers=3, nfsvers=4.1
