apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsv3-mount-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfsv3-mount-sc
