apiVersion: v1
kind: Pod
metadata:
  name: multi-node-rwx-pod-b
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1.ocp.ngxlabocp.com
  containers:
  - name: client-container
    image: nginx
    volumeMounts:
    - name: multi-node-rwx-pvc
      mountPath: /data
      readOnly: false
  volumes:
  - name: multi-node-rwx-pvc
    persistentVolumeClaim:
      claimName: multi-node-rwx-pvc
