apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-resize-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      # Start small; grow with: oc patch pvc volume-resize-pvc --patch '{"spec":{"resources":{"requests":{"storage":"2Gi"}}}}'
      storage: 1Gi
  storageClassName: volume-resize-sc
