apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-pvc-single-pod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: single-pvc-single-pod-sc