apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nfs.csi.ngxstorage.com
spec:
  attachRequired: true
  fsGroupPolicy: None
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-ngxstorage
provisioner: nfs.csi.ngxstorage.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  blocksize: 128k
  deduplication: "on"
  compression: "on"
  thin_provision: "on"
  permissions: "111111101"
