{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  storage-ips: {{ required "secret.storageIPs is required when secret.create=true" .Values.secret.storageIPs | quote }}
  pool-name: {{ required "secret.poolName is required when secret.create=true" .Values.secret.poolName | quote }}
  api-key: {{ required "secret.apiKey is required when secret.create=true" .Values.secret.apiKey | quote }}
  data-ip: {{ required "secret.dataIP is required when secret.create=true" .Values.secret.dataIP | quote }}
{{- end }}
