apiVersion: v1
entries:
  nfs-csi-ngxstorage:
  - annotations:
      charts.openshift.io/name: NGX Storage NFS CSI Driver
      charts.openshift.io/provider: NGX Storage
      charts.openshift.io/supportURL: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    apiVersion: v2
    appVersion: 2.0.3-3
    created: "2026-08-14T12:43:04.322086425Z"
    description: NGX Storage NFS CSI Driver — provisions NFS shares from NGX Storage
      Manager
    digest: 3856309ed5e8d36ae951b53dfeb7e18e8693bb3348a69416548575dc1f2daa6d
    home: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    keywords:
    - csi
    - nfs
    - ngxstorage
    - storage
    kubeVersion: '>=1.28.0'
    maintainers:
    - email: k8s@ngxstorage.com
      name: NGX Storage
    name: nfs-csi-ngxstorage
    sources:
    - https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    type: application
    urls:
    - https://ngxstorage.github.io/nfs-csi-ngxstorage-driver/nfs-csi-ngxstorage-0.1.2.tgz
    version: 0.1.2
  - annotations:
      charts.openshift.io/name: NGX Storage NFS CSI Driver
      charts.openshift.io/provider: NGX Storage
      charts.openshift.io/supportURL: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    apiVersion: v2
    appVersion: 2.0.3
    created: "2026-08-14T12:43:04.321702395Z"
    description: NGX Storage NFS CSI Driver — provisions NFS shares from NGX Storage
      Manager
    digest: 721cbbc4db08262bf688c782a1751d6e551ce9ab28faba1171cb8825a41f37ee
    home: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    keywords:
    - csi
    - nfs
    - ngxstorage
    - storage
    kubeVersion: '>=1.28.0'
    maintainers:
    - email: k8s@ngxstorage.com
      name: NGX Storage
    name: nfs-csi-ngxstorage
    sources:
    - https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    type: application
    urls:
    - https://ngxstorage.github.io/nfs-csi-ngxstorage-driver/nfs-csi-ngxstorage-0.1.1.tgz
    version: 0.1.1
  - annotations:
      charts.openshift.io/name: NGX Storage NFS CSI Driver
      charts.openshift.io/provider: NGX Storage
      charts.openshift.io/supportURL: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    apiVersion: v2
    appVersion: 2.0.3
    created: "2026-08-14T12:43:04.321304209Z"
    description: NGX Storage NFS CSI Driver — provisions NFS shares from NGX Storage
      Manager
    digest: 8b29ec5a51e20f1c13484b58dbf388603a8f1310f553c88ec464e7969c02d05d
    home: https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    keywords:
    - csi
    - nfs
    - ngxstorage
    - storage
    kubeVersion: '>=1.28.0'
    maintainers:
    - email: k8s@ngxstorage.com
      name: NGX Storage
    name: nfs-csi-ngxstorage
    sources:
    - https://github.com/NGXStorage/nfs-csi-ngxstorage-driver
    type: application
    urls:
    - https://ngxstorage.github.io/nfs-csi-ngxstorage-driver/nfs-csi-ngxstorage-0.1.0.tgz
    version: 0.1.0
generated: "2026-08-14T12:43:04.320770679Z"
