apiVersion: v1
kind: Secret
metadata:
  name: nfs-csi-ngxstorage-config
  namespace: nfs-csi-ngxstorage
type: Opaque
stringData:
  storage-ips: "192.168.1.201,192.168.1.202"   # NGX Storage Manager IPs (comma-separated)
  pool-name: "POOLNAME"                         # NGX storage pool name
  api-key: "APIKEY"                             # NGX Storage Manager API key
  data-ip: "10.10.10.10"                        # NGX NFS data path IP
