apiVersion: v1
kind: Pod
metadata:
  name: snapshot-restore-source-pod
  namespace: default
spec:
  containers:
  - name: client-container
    image: nginx
    volumeMounts:
    - name: snapshot-restore-source-pvc
      mountPath: /data
      readOnly: false
  volumes:
  - name: snapshot-restore-source-pvc
    persistentVolumeClaim:
      claimName: snapshot-restore-source-pvc
