apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-restore-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  # Restore a new volume from the snapshot taken of the source PVC.
  dataSource:
    name: snapshot-restore-vs
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      # Must be >= snapshot size.
      storage: 1Gi
  storageClassName: snapshot-restore-sc
